# Generated by Django 2.0.1 on 2020-05-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200507_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(default='', max_length=511),
            preserve_default=False,
        ),
    ]
