# Generated by Django 2.0.1 on 2020-05-08 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0005_auto_20200508_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='shared',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
